-- Gridiron Legacy — the whole schema, in order.
--
-- Generated by scripts/build-migration.mjs. Do not edit this file; edit the
-- migrations it is built from and run the script again.
--
-- Paste the whole thing into the Supabase SQL editor and run it once. It is
-- wrapped in a transaction, so a failure anywhere leaves the database
-- untouched rather than half migrated.
--
-- Built from 9 migrations:
--   0001_schema.sql
--   0002_trades.sql
--   0003_draft.sql
--   0004_auth.sql
--   0005_team_count.sql
--   0006_draft_control.sql
--   0007_waivers.sql
--   0008_schedule.sql
--   0009_divisions.sql

begin;


-- ======================================================================
-- 0001_schema.sql
-- ======================================================================

-- Gridiron Legacy — shared league state.
--
-- Everything here replaces what the prototype kept in localStorage, where each
-- manager got a private copy of the league. One row per league, and every other
-- table hangs off it.

create extension if not exists pgcrypto;

create table leagues (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  season int not null default 2026,
  commissioner_slot text,
  settings jsonb not null default '{}'::jsonb,
  lottery_order text[],
  draft_at timestamptz,
  -- The server's clock for the draft. Every client counts down from this
  -- rather than its own, so twelve clocks cannot drift apart.
  pick_started_at timestamptz,
  created_at timestamptz not null default now()
);

-- One row per manager. slot is the franchise code: STL, BLZ, HELX…
create table managers (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  slot text not null,
  name text not null,
  franchise text not null,
  -- null means the manager must set a PIN on next sign-in. The commissioner
  -- clears this; they never set one, so they cannot sign in as another team.
  pin_hash text,
  is_commissioner boolean not null default false,
  ready boolean not null default false,
  created_at timestamptz not null default now(),
  unique (league_id, slot)
);

create table roster_slots (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  manager_id uuid not null references managers(id) on delete cascade,
  player_name text not null,
  acquired text not null default 'draft' check (acquired in ('draft','trade','waiver')),
  overall_pick int,
  lineup_slot text not null default 'BENCH',
  -- A player belongs to exactly one roster in a league. This is what makes two
  -- managers clicking the same player in the same second resolve cleanly.
  unique (league_id, player_name)
);

create index roster_slots_manager_idx on roster_slots (manager_id);

create table draft_picks (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  overall int not null,
  round int not null,
  manager_id uuid references managers(id) on delete set null,
  player_name text,
  picked_at timestamptz,
  unique (league_id, overall)
);

create table trades (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  from_manager uuid not null references managers(id) on delete cascade,
  to_manager uuid not null references managers(id) on delete cascade,
  offer jsonb not null,
  status text not null default 'open'
    check (status in ('open','countered','agreed','executed','declined')),
  from_accepted boolean not null default false,
  to_accepted boolean not null default false,
  thread jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  executed_at timestamptz
);

create table trade_block (
  league_id uuid not null references leagues(id) on delete cascade,
  player_name text not null,
  manager_id uuid not null references managers(id) on delete cascade,
  listed_at timestamptz not null default now(),
  primary key (league_id, player_name)
);

-- Live fantasy scoring, written by the ESPN ingestion job.
create table player_scores (
  league_id uuid not null references leagues(id) on delete cascade,
  week int not null,
  player_name text not null,
  points numeric not null default 0,
  stat_line text,
  updated_at timestamptz not null default now(),
  primary key (league_id, week, player_name)
);

-- ---------------------------------------------------------------------------
-- Weekly pick-'em
-- ---------------------------------------------------------------------------

-- The NFL schedule for a week, mirrored from ESPN's scoreboard so picks have a
-- stable set of games to reference and grading does not depend on ESPN being
-- reachable at that moment.
create table nfl_games (
  id text primary key,                       -- ESPN event id
  season int not null,
  week int not null,
  season_type int not null default 2,
  starts_at timestamptz not null,
  home_team text not null,
  away_team text not null,
  home_score int not null default 0,
  away_score int not null default 0,
  state text not null default 'pre' check (state in ('pre','in','post')),
  -- Null until the game is final; a tie stays null with completed = true.
  winner text,
  completed boolean not null default false,
  updated_at timestamptz not null default now()
);

create index nfl_games_week_idx on nfl_games (season, week);

create table pickem_picks (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  manager_id uuid not null references managers(id) on delete cascade,
  game_id text not null references nfl_games(id) on delete cascade,
  -- The team abbreviation the manager took.
  pick text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- One pick per manager per game; changing a pick updates this row.
  unique (manager_id, game_id)
);

create index pickem_picks_league_idx on pickem_picks (league_id, game_id);

-- Snapshots taken before a destructive commissioner action.
create table roster_backups (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  kind text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table admin_log (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  actor uuid references managers(id) on delete set null,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- Without this, any manager can edit any roster from the browser console.
-- Reads are league-wide; writes are limited to the manager's own rows, and
-- destructive changes to the commissioner.
-- ---------------------------------------------------------------------------

alter table leagues        enable row level security;
alter table managers       enable row level security;
alter table roster_slots   enable row level security;
alter table draft_picks    enable row level security;
alter table trades         enable row level security;
alter table trade_block    enable row level security;
alter table player_scores  enable row level security;
alter table nfl_games      enable row level security;
alter table pickem_picks   enable row level security;
alter table roster_backups enable row level security;
alter table admin_log      enable row level security;

-- The signed-in manager's own row, used by every policy below.
create or replace function current_manager()
returns managers
language sql
stable
security definer
set search_path = public
as $$
  select * from managers where auth_user_id = auth.uid() limit 1;
$$;

create or replace function current_league()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select league_id from managers where auth_user_id = auth.uid() limit 1;
$$;

create or replace function is_commissioner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_commissioner from managers where auth_user_id = auth.uid() limit 1), false);
$$;

-- Read: anyone signed in sees their own league.
create policy leagues_read on leagues
  for select using (id = current_league());

create policy managers_read on managers
  for select using (league_id = current_league());

create policy roster_read on roster_slots
  for select using (league_id = current_league());

create policy picks_read on draft_picks
  for select using (league_id = current_league());

create policy trades_read on trades
  for select using (league_id = current_league());

create policy block_read on trade_block
  for select using (league_id = current_league());

create policy scores_read on player_scores
  for select using (league_id = current_league());

create policy pickem_read on pickem_picks
  for select using (league_id = current_league());

-- The NFL schedule is not league-specific and is safe for any signed-in user.
create policy games_read on nfl_games
  for select using (auth.uid() is not null);

-- Write: a manager owns their own roster, block entries, trades and picks.
create policy roster_write on roster_slots
  for update using (manager_id = (select id from current_manager()));

create policy block_write on trade_block
  for all using (manager_id = (select id from current_manager()))
  with check (manager_id = (select id from current_manager()));

create policy trades_write on trades
  for insert with check (from_manager = (select id from current_manager()));

create policy trades_respond on trades
  for update using (
    from_manager = (select id from current_manager())
    or to_manager = (select id from current_manager())
  );

-- A manager may only ever write their own pick, and only before kickoff.
create policy pickem_write on pickem_picks
  for all using (manager_id = (select id from current_manager()))
  with check (
    manager_id = (select id from current_manager())
    and league_id = current_league()
    and exists (
      select 1 from nfl_games g
      where g.id = game_id and g.starts_at > now()
    )
  );

-- A manager may set their own ready flag and franchise name, nothing else.
create policy managers_self_update on managers
  for update using (auth_user_id = auth.uid());

-- Commissioner-only surfaces.
create policy leagues_admin on leagues
  for update using (id = current_league() and is_commissioner());

create policy roster_admin on roster_slots
  for all using (league_id = current_league() and is_commissioner())
  with check (league_id = current_league() and is_commissioner());

create policy managers_admin on managers
  for update using (league_id = current_league() and is_commissioner());

create policy backups_admin on roster_backups
  for all using (league_id = current_league() and is_commissioner())
  with check (league_id = current_league() and is_commissioner());

create policy admin_log_read on admin_log
  for select using (league_id = current_league() and is_commissioner());

-- player_scores and nfl_games are written only by the ingestion job, which
-- uses the service key and bypasses RLS. No write policy is granted, so no
-- browser session can forge a score.


-- ======================================================================
-- 0002_trades.sql
-- ======================================================================

-- Trade execution.
--
-- A trade moves players between two rosters. That has to be one atomic step:
-- if it half-applied, a player would be on both rosters or on neither. The
-- Supabase client cannot open a transaction, so execution lives here as a
-- single function and the API only ever calls this.

-- Who proposed, who received, and what each side sends. `offer` is
--   { "give": ["Player A", …], "get": ["Player B", …] }
-- where `give` leaves from_manager and `get` leaves to_manager.

create or replace function execute_trade(p_trade_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trade      trades;
  v_me         managers;
  v_give       text[];
  v_get        text[];
  v_moved      int;
  v_expected   int;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null then
    raise exception 'Not signed in' using errcode = '28000';
  end if;

  -- Lock the row for the duration, so two managers hitting accept at the same
  -- moment cannot both execute the same trade.
  select * into v_trade from trades where id = p_trade_id for update;
  if v_trade.id is null then
    raise exception 'No such trade' using errcode = 'P0002';
  end if;

  if v_me.id <> v_trade.from_manager and v_me.id <> v_trade.to_manager then
    raise exception 'Not your trade' using errcode = '42501';
  end if;

  if v_trade.status = 'executed' then
    raise exception 'This trade has already been executed' using errcode = '55000';
  end if;

  if not (v_trade.from_accepted and v_trade.to_accepted) then
    raise exception 'Both managers must accept first' using errcode = '55000';
  end if;

  v_give := coalesce(array(select jsonb_array_elements_text(v_trade.offer -> 'give')), '{}');
  v_get  := coalesce(array(select jsonb_array_elements_text(v_trade.offer -> 'get')),  '{}');

  if array_length(v_give, 1) is null and array_length(v_get, 1) is null then
    raise exception 'An empty trade cannot be executed' using errcode = '55000';
  end if;

  -- The rosters may have changed since the offer was made. Every player named
  -- must still be owned by the side that promised him, or the whole trade is
  -- void — never a partial move.
  v_expected := coalesce(array_length(v_give, 1), 0);
  select count(*) into v_moved
  from roster_slots
  where league_id = v_trade.league_id
    and manager_id = v_trade.from_manager
    and player_name = any (v_give);

  if v_moved <> v_expected then
    raise exception 'A player in this offer is no longer on the proposing roster'
      using errcode = '55000';
  end if;

  v_expected := coalesce(array_length(v_get, 1), 0);
  select count(*) into v_moved
  from roster_slots
  where league_id = v_trade.league_id
    and manager_id = v_trade.to_manager
    and player_name = any (v_get);

  if v_moved <> v_expected then
    raise exception 'A player in this offer is no longer on the receiving roster'
      using errcode = '55000';
  end if;

  -- The move itself. Players land on the bench: a lineup slot on one roster
  -- means nothing on another, and the new owner sets it.
  update roster_slots
     set manager_id = v_trade.to_manager,
         acquired = 'trade',
         lineup_slot = 'BENCH'
   where league_id = v_trade.league_id
     and manager_id = v_trade.from_manager
     and player_name = any (v_give);

  update roster_slots
     set manager_id = v_trade.from_manager,
         acquired = 'trade',
         lineup_slot = 'BENCH'
   where league_id = v_trade.league_id
     and manager_id = v_trade.to_manager
     and player_name = any (v_get);

  update trades
     set status = 'executed',
         executed_at = now()
   where id = p_trade_id;

  -- A traded player is no longer on offer.
  delete from trade_block
   where league_id = v_trade.league_id
     and player_name = any (v_give || v_get);

  insert into admin_log (league_id, actor, action, detail)
  values (v_trade.league_id, v_me.id, 'trade_executed',
          jsonb_build_object('trade_id', p_trade_id, 'offer', v_trade.offer));

  return jsonb_build_object(
    'ok', true,
    'trade_id', p_trade_id,
    'give', to_jsonb(v_give),
    'get', to_jsonb(v_get)
  );
end;
$$;

revoke all on function execute_trade(uuid) from public;
grant execute on function execute_trade(uuid) to authenticated;

-- Accepting is the only field a counterparty may flip, and changing the terms
-- must void both acceptances. Doing that in a trigger means a client cannot
-- accept on one set of terms and have them swapped underneath.
create or replace function void_acceptance_on_change()
returns trigger
language plpgsql
as $$
begin
  if new.offer is distinct from old.offer then
    new.from_accepted := false;
    new.to_accepted := false;
    new.status := 'countered';
  end if;
  return new;
end;
$$;

create trigger trades_void_acceptance
  before update on trades
  for each row
  execute function void_acceptance_on_change();


-- ======================================================================
-- 0003_draft.sql
-- ======================================================================

-- The live draft.
--
-- Twelve people, one board, one clock. Two things must hold no matter how many
-- browsers are open: a player can be taken exactly once, and every client
-- agrees on whose turn it is. Both are settled here rather than in any client.

-- Each manager's own queue, used by autodraft when their clock runs out.
create table draft_queue (
  league_id uuid not null references leagues(id) on delete cascade,
  manager_id uuid not null references managers(id) on delete cascade,
  player_name text not null,
  rank int not null,
  primary key (manager_id, player_name)
);

create index draft_queue_order_idx on draft_queue (manager_id, rank);

alter table draft_queue enable row level security;

create policy queue_read on draft_queue
  for select using (manager_id = (select id from current_manager()));

create policy queue_write on draft_queue
  for all using (manager_id = (select id from current_manager()))
  with check (manager_id = (select id from current_manager()));

-- Draft state lives on the league row. pick_started_at already exists; this
-- adds where the draft has reached and whether it is running.
alter table leagues
  add column if not exists draft_state text not null default 'pending'
    check (draft_state in ('pending', 'running', 'paused', 'complete')),
  add column if not exists current_pick int not null default 1;

/**
 * Makes one pick. Everything that could go wrong with twelve people clicking
 * at once is checked here, inside one transaction:
 *   - the draft is actually running
 *   - it is this manager's turn (or the commissioner is acting for them)
 *   - the player is not already on someone's roster
 * The unique constraint on roster_slots is the final backstop: if two calls
 * race past the check, the second fails rather than duplicating the player.
 */
create or replace function make_pick(
  p_league_id uuid,
  p_player_name text,
  p_manager_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me       managers;
  v_league   leagues;
  v_pick     draft_picks;
  v_actor    uuid;
  v_rounds   int;
  v_teams    int;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null then
    raise exception 'Not signed in' using errcode = '28000';
  end if;

  -- Lock the league row: this serialises every pick in the draft, so two
  -- managers cannot both believe it is their turn.
  select * into v_league from leagues where id = p_league_id for update;
  if v_league.id is null then
    raise exception 'No such league' using errcode = 'P0002';
  end if;

  if v_me.league_id <> p_league_id then
    raise exception 'Not your league' using errcode = '42501';
  end if;

  if v_league.draft_state <> 'running' then
    raise exception 'The draft is not running' using errcode = '55000';
  end if;

  -- The commissioner may pick on behalf of a manager who is not there.
  v_actor := coalesce(p_manager_id, v_me.id);
  if v_actor <> v_me.id and not v_me.is_commissioner then
    raise exception 'Only the commissioner can pick for another manager'
      using errcode = '42501';
  end if;

  select * into v_pick
    from draft_picks
   where league_id = p_league_id
     and overall = v_league.current_pick;

  if v_pick.id is null then
    raise exception 'The draft board has no pick % ', v_league.current_pick
      using errcode = 'P0002';
  end if;

  if v_pick.player_name is not null then
    raise exception 'That pick has already been made' using errcode = '55000';
  end if;

  if v_pick.manager_id <> v_actor then
    raise exception 'It is not your pick' using errcode = '55000';
  end if;

  -- A player already rostered cannot be drafted. The unique index on
  -- (league_id, player_name) enforces this even if two calls race here.
  if exists (
    select 1 from roster_slots
     where league_id = p_league_id and player_name = p_player_name
  ) then
    raise exception 'That player is already rostered' using errcode = '23505';
  end if;

  insert into roster_slots (league_id, manager_id, player_name, acquired, overall_pick, lineup_slot)
  values (p_league_id, v_actor, p_player_name, 'draft', v_pick.overall, 'BENCH');

  update draft_picks
     set player_name = p_player_name,
         picked_at = now()
   where id = v_pick.id;

  -- A drafted player is off everyone's queue, not just the picker's.
  delete from draft_queue
   where league_id = p_league_id and player_name = p_player_name;

  select count(*) into v_rounds from draft_picks where league_id = p_league_id;
  select count(*) into v_teams from managers where league_id = p_league_id;

  -- Advance the board and restart the clock from the server, so every client
  -- counts down from the same instant rather than its own.
  update leagues
     set current_pick = v_league.current_pick + 1,
         pick_started_at = now(),
         draft_state = case
           when v_league.current_pick + 1 > v_rounds then 'complete'
           else 'running'
         end
   where id = p_league_id;

  return jsonb_build_object(
    'ok', true,
    'overall', v_pick.overall,
    'round', v_pick.round,
    'manager_id', v_actor,
    'player_name', p_player_name,
    'next_pick', v_league.current_pick + 1
  );
end;
$$;

revoke all on function make_pick(uuid, text, uuid) from public;
grant execute on function make_pick(uuid, text, uuid) to authenticated;

/**
 * Autodraft. A browser that closed cannot pick for itself, so when a clock
 * expires this takes the top of that manager's queue, or the best available
 * by ADP rank if the queue is empty. Called by the draft cron, which runs
 * with the service key.
 */
create or replace function autodraft_expired(p_league_id uuid, p_fallback text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_league  leagues;
  v_pick    draft_picks;
  v_name    text;
begin
  select * into v_league from leagues where id = p_league_id for update;

  if v_league.id is null or v_league.draft_state <> 'running' then
    return jsonb_build_object('ok', false, 'reason', 'not running');
  end if;

  -- Still on the clock, nothing to do.
  if v_league.pick_started_at is null
     or now() < v_league.pick_started_at
              + make_interval(secs => coalesce((v_league.settings ->> 'pickSeconds')::int, 90)) then
    return jsonb_build_object('ok', false, 'reason', 'on the clock');
  end if;

  select * into v_pick
    from draft_picks
   where league_id = p_league_id and overall = v_league.current_pick;

  if v_pick.id is null or v_pick.player_name is not null then
    return jsonb_build_object('ok', false, 'reason', 'no open pick');
  end if;

  -- The manager's own queue first, skipping anyone already taken.
  select q.player_name into v_name
    from draft_queue q
   where q.manager_id = v_pick.manager_id
     and not exists (
       select 1 from roster_slots r
        where r.league_id = p_league_id and r.player_name = q.player_name
     )
   order by q.rank
   limit 1;

  if v_name is null then v_name := p_fallback; end if;
  if v_name is null then
    return jsonb_build_object('ok', false, 'reason', 'nothing to pick');
  end if;

  insert into roster_slots (league_id, manager_id, player_name, acquired, overall_pick, lineup_slot)
  values (p_league_id, v_pick.manager_id, v_name, 'draft', v_pick.overall, 'BENCH');

  update draft_picks
     set player_name = v_name, picked_at = now()
   where id = v_pick.id;

  delete from draft_queue where league_id = p_league_id and player_name = v_name;

  update leagues
     set current_pick = v_league.current_pick + 1,
         pick_started_at = now(),
         draft_state = case
           when v_league.current_pick + 1
                > (select count(*) from draft_picks where league_id = p_league_id)
           then 'complete' else 'running' end
   where id = p_league_id;

  insert into admin_log (league_id, actor, action, detail)
  values (p_league_id, v_pick.manager_id, 'autodraft',
          jsonb_build_object('overall', v_pick.overall, 'player_name', v_name));

  return jsonb_build_object('ok', true, 'overall', v_pick.overall, 'player_name', v_name);
end;
$$;

revoke all on function autodraft_expired(uuid, text) from public;

-- Realtime: clients subscribe to picks landing rather than polling the board.
alter publication supabase_realtime add table draft_picks;
alter publication supabase_realtime add table leagues;


-- ======================================================================
-- 0004_auth.sql
-- ======================================================================

-- Sign-in attempt log, so a four-digit PIN cannot be walked in a loop.
--
-- A four-digit PIN is 10,000 possibilities: fine for a league of friends,
-- trivial to brute-force without this.

create table pin_attempts (
  id bigserial primary key,
  league_id uuid not null references leagues(id) on delete cascade,
  slot text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index pin_attempts_recent_idx on pin_attempts (league_id, slot, attempted_at desc);

alter table pin_attempts enable row level security;
-- Written only by the sign-in route, which holds the service key. No browser
-- session may read or forge an attempt record.

/**
 * How many failed attempts a slot has made since the last success, within the
 * window. The sign-in route locks the slot out once this passes the limit.
 */
create or replace function recent_pin_failures(
  p_league_id uuid,
  p_slot text,
  p_window interval default interval '15 minutes'
)
returns int
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::int
    from pin_attempts
   where league_id = p_league_id
     and slot = p_slot
     and not succeeded
     and attempted_at > now() - p_window
     and attempted_at > coalesce(
       (select max(attempted_at) from pin_attempts
         where league_id = p_league_id and slot = p_slot and succeeded),
       '-infinity'::timestamptz
     );
$$;

/**
 * Clears a manager's PIN. The commissioner calls this; it does not set a new
 * PIN, it forces the manager to choose one on next sign-in.
 *
 * This shape matters: if a commissioner could set another manager's PIN, they
 * could sign in as any team in the league.
 */
create or replace function clear_pin(p_manager_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me managers;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null or not v_me.is_commissioner then
    raise exception 'Only the commissioner can reset a PIN' using errcode = '42501';
  end if;

  update managers
     set pin_hash = null
   where id = p_manager_id
     and league_id = v_me.league_id;

  if not found then
    raise exception 'No such manager in your league' using errcode = 'P0002';
  end if;

  insert into admin_log (league_id, actor, action, detail)
  values (v_me.league_id, v_me.id, 'pin_cleared',
          jsonb_build_object('manager_id', p_manager_id));

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function clear_pin(uuid) from public;
grant execute on function clear_pin(uuid) to authenticated;


-- ======================================================================
-- 0005_team_count.sql
-- ======================================================================

-- League size, and the draft board derived from it.
--
-- The board is not data a commissioner types in — it is generated from the
-- number of franchises and the number of rounds. So changing the league size
-- has to regenerate it, and that is only ever safe before the draft starts.

/**
 * Rebuilds the snake draft board from the league's current franchises.
 *
 * Order is the lottery order if one has been drawn, otherwise slot order.
 * Odd rounds run in that order, even rounds reverse it — that is the snake.
 *
 * Refuses once any pick has been made. Regenerating a board mid-draft would
 * renumber picks that already have players against them.
 */
create or replace function rebuild_draft_board(p_league_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_league   leagues;
  v_rounds   int;
  v_teams    int;
  v_made     int;
  v_order    uuid[];
  v_round    int;
  v_seat     int;
  v_overall  int := 0;
begin
  select * into v_league from leagues where id = p_league_id for update;
  if v_league.id is null then
    raise exception 'No such league' using errcode = 'P0002';
  end if;

  select count(*) into v_made
    from draft_picks
   where league_id = p_league_id and player_name is not null;

  if v_made > 0 then
    raise exception 'The draft has already started — % picks are made', v_made
      using errcode = '55000';
  end if;

  v_rounds := coalesce((v_league.settings ->> 'rounds')::int, 24);

  -- Draft order: the lottery if it has been drawn, else by slot.
  if v_league.lottery_order is not null and array_length(v_league.lottery_order, 1) > 0 then
    select array_agg(m.id order by idx)
      into v_order
      from unnest(v_league.lottery_order) with ordinality as lo(slot, idx)
      join managers m on m.league_id = p_league_id and m.slot = lo.slot;
  else
    select array_agg(id order by slot) into v_order
      from managers where league_id = p_league_id;
  end if;

  v_teams := coalesce(array_length(v_order, 1), 0);
  if v_teams = 0 then
    raise exception 'The league has no franchises' using errcode = '55000';
  end if;

  delete from draft_picks where league_id = p_league_id;

  for v_round in 1..v_rounds loop
    for v_seat in 1..v_teams loop
      v_overall := v_overall + 1;
      insert into draft_picks (league_id, overall, round, manager_id)
      values (
        p_league_id,
        v_overall,
        v_round,
        -- Odd rounds run forward, even rounds back.
        v_order[case when v_round % 2 = 1 then v_seat else v_teams - v_seat + 1 end]
      );
    end loop;
  end loop;

  update leagues
     set current_pick = 1,
         pick_started_at = null,
         draft_state = case when draft_state = 'complete' then 'pending' else draft_state end
   where id = p_league_id;

  return jsonb_build_object('ok', true, 'teams', v_teams, 'rounds', v_rounds, 'picks', v_overall);
end;
$$;

revoke all on function rebuild_draft_board(uuid) from public;

/**
 * Sets how many franchises the league has.
 *
 * Growing adds open, unclaimed slots. Shrinking only ever removes slots that
 * nobody has claimed and that hold no players — a manager who has signed up
 * or drafted is never deleted out from under themselves; the call fails and
 * names them instead.
 *
 * The board is rebuilt either way, so the draft always matches the league.
 */
create or replace function set_team_count(p_league_id uuid, p_count int)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me       managers;
  v_current  int;
  v_blocked  text[];
  v_removing uuid[];
  v_slot     text;
  v_i        int;
  v_made     int;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null or not v_me.is_commissioner or v_me.league_id <> p_league_id then
    raise exception 'Only the commissioner can change the league size'
      using errcode = '42501';
  end if;

  if p_count < 2 or p_count > 16 then
    raise exception 'A league runs from 2 to 16 franchises' using errcode = '22003';
  end if;

  select count(*) into v_made
    from draft_picks
   where league_id = p_league_id and player_name is not null;

  if v_made > 0 then
    raise exception 'The draft has already started — the league size is fixed now'
      using errcode = '55000';
  end if;

  select count(*) into v_current from managers where league_id = p_league_id;

  if p_count < v_current then
    -- The slots that would go: the highest-lettered ones, newest first.
    select array_agg(id order by slot desc)
      into v_removing
      from (
        select id, slot from managers
         where league_id = p_league_id
         order by slot desc
         limit (v_current - p_count)
      ) doomed;

    -- Anyone claimed or holding players blocks the change by name.
    select array_agg(distinct m.franchise)
      into v_blocked
      from managers m
     where m.id = any (v_removing)
       and (
         m.pin_hash is not null
         or exists (select 1 from roster_slots r where r.manager_id = m.id)
       );

    if v_blocked is not null then
      raise exception 'These franchises are claimed or hold players: %',
        array_to_string(v_blocked, ', ')
        using errcode = '55000';
    end if;

    delete from managers where id = any (v_removing);

  elsif p_count > v_current then
    for v_i in (v_current + 1)..p_count loop
      -- Slots are T01, T02… only where the seeded names run out, so a league
      -- that shrinks and grows again does not collide with a surviving slot.
      v_slot := 'T' || lpad(v_i::text, 2, '0');
      while exists (select 1 from managers where league_id = p_league_id and slot = v_slot) loop
        v_slot := v_slot || 'X';
      end loop;

      insert into managers (league_id, slot, name, franchise, pin_hash, is_commissioner)
      values (p_league_id, v_slot, 'Open', 'Franchise ' || v_i, null, false);
    end loop;
  end if;

  perform rebuild_draft_board(p_league_id);

  insert into admin_log (league_id, actor, action, detail)
  values (p_league_id, v_me.id, 'team_count_changed',
          jsonb_build_object('from', v_current, 'to', p_count));

  return jsonb_build_object('ok', true, 'teams', p_count, 'was', v_current);
end;
$$;

revoke all on function set_team_count(uuid, int) from public;
grant execute on function set_team_count(uuid, int) to authenticated;

-- The commissioner may also rebuild the board on its own, after redrawing the
-- lottery or changing the number of rounds.
create or replace function commissioner_rebuild_board(p_league_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me managers;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null or not v_me.is_commissioner or v_me.league_id <> p_league_id then
    raise exception 'Only the commissioner can rebuild the draft board'
      using errcode = '42501';
  end if;

  return rebuild_draft_board(p_league_id);
end;
$$;

revoke all on function commissioner_rebuild_board(uuid) from public;
grant execute on function commissioner_rebuild_board(uuid) to authenticated;


-- ======================================================================
-- 0006_draft_control.sql
-- ======================================================================

-- Starting, pausing and resuming the draft.
--
-- The clock lives on the league row, so starting and resuming both have to
-- reset pick_started_at — otherwise a draft resumed after an hour's pause
-- would show every client a clock that expired long ago and autodraft the
-- manager who was on it.

create or replace function set_draft_state(p_league_id uuid, p_state text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me      managers;
  v_league  leagues;
  v_open    int;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null or not v_me.is_commissioner or v_me.league_id <> p_league_id then
    raise exception 'Only the commissioner can control the draft' using errcode = '42501';
  end if;

  if p_state not in ('pending', 'running', 'paused', 'complete') then
    raise exception 'Unknown draft state %', p_state using errcode = '22023';
  end if;

  select * into v_league from leagues where id = p_league_id for update;

  if p_state = 'running' then
    select count(*) into v_open
      from draft_picks
     where league_id = p_league_id and player_name is null;

    if v_open = 0 then
      raise exception 'Every pick has been made' using errcode = '55000';
    end if;

    -- Resume from the first pick still open, so a board that was rebuilt or a
    -- draft that was paused mid-round picks up in the right place.
    update leagues
       set draft_state = 'running',
           current_pick = (
             select min(overall) from draft_picks
              where league_id = p_league_id and player_name is null
           ),
           -- The clock restarts now. A paused draft must not resume onto an
           -- expired clock and autodraft whoever was on it.
           pick_started_at = now()
     where id = p_league_id;
  else
    update leagues
       set draft_state = p_state,
           pick_started_at = case when p_state = 'paused' then null else pick_started_at end
     where id = p_league_id;
  end if;

  insert into admin_log (league_id, actor, action, detail)
  values (p_league_id, v_me.id, 'draft_state', jsonb_build_object('to', p_state));

  return jsonb_build_object('ok', true, 'state', p_state);
end;
$$;

revoke all on function set_draft_state(uuid, text) from public;
grant execute on function set_draft_state(uuid, text) to authenticated;

-- autodraft_expired already refuses when pick_started_at is null, which is how
-- a paused draft is safe from it.


-- ======================================================================
-- 0007_waivers.sql
-- ======================================================================

-- Waivers and free agency.
--
-- Two ways a roster changes outside a trade: a waiver claim, which competes
-- with other managers and is settled in priority order by a scheduled run; and
-- an open-market add, which is first come, first served. Which applies is the
-- league's waiverMode setting.
--
-- Everything that decides who gets a player is here rather than in a route,
-- because two managers claiming the same player in the same second must have
-- exactly one winner.

-- An open-market pickup is not a waiver claim — nobody competed for it — so
-- it is recorded as its own kind rather than being filed under 'waiver'.
alter table roster_slots
  drop constraint if exists roster_slots_acquired_check;

alter table roster_slots
  add constraint roster_slots_acquired_check
  check (acquired in ('draft', 'trade', 'waiver', 'add'));

-- Rolling waiver priority. Lower is better; winning a claim sends you last.
alter table managers
  add column if not exists waiver_priority int;

-- Seed priority by slot for a league that has none, so the order is defined
-- from the first claim rather than being null.
update managers m
   set waiver_priority = seq.rn
  from (
    select id, row_number() over (partition by league_id order by slot) as rn
      from managers
  ) seq
 where seq.id = m.id and m.waiver_priority is null;

create table waiver_claims (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  manager_id uuid not null references managers(id) on delete cascade,
  add_player text not null,
  -- What they will drop to make room. Null when the roster has space.
  drop_player text,
  -- A manager's own ordering across their claims: 1 is tried first.
  claim_order int not null default 1,
  status text not null default 'pending'
    check (status in ('pending', 'won', 'lost', 'cancelled')),
  reason text,
  created_at timestamptz not null default now(),
  settled_at timestamptz,
  unique (league_id, manager_id, add_player)
);

create index waiver_claims_pending_idx
  on waiver_claims (league_id, status, claim_order);

alter table waiver_claims enable row level security;

-- A manager sees and manages only their own claims: knowing what everyone else
-- has claimed before the run would defeat the point of a blind waiver period.
create policy claims_own on waiver_claims
  for all using (manager_id = (select id from current_manager()))
  with check (manager_id = (select id from current_manager()));

-- Every roster change, so "where did he go?" has an answer.
create table transactions (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  manager_id uuid references managers(id) on delete set null,
  kind text not null,                    -- add | drop | waiver | trade | draft
  player_name text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index transactions_recent_idx on transactions (league_id, created_at desc);

alter table transactions enable row level security;

create policy transactions_read on transactions
  for select using (
    league_id = (select league_id from current_manager())
  );

/** How many players a roster holds, starters plus bench. IR sits outside it. */
create or replace function roster_capacity(p_settings jsonb)
returns int
language sql
immutable
as $$
  select coalesce(
           (select sum(value::int)::int from jsonb_each_text(coalesce(p_settings -> 'starters', '{}'::jsonb))),
           0
         )
       + coalesce((p_settings ->> 'bench')::int, 0);
$$;

/** How many a manager currently holds against that capacity. */
create or replace function roster_count(p_manager_id uuid)
returns int
language sql
stable
as $$
  select count(*)::int from roster_slots
   where manager_id = p_manager_id and lineup_slot is distinct from 'IR';
$$;

/**
 * Puts a player on a roster, dropping one if it is full.
 *
 * This is the mechanism with no opinion about who is asking: the waiver run
 * calls it for the winning manager, and add_player() calls it for the caller.
 * Keeping the authorisation out of here means the rule about who may act is
 * stated once, in add_player, rather than inferred from whether auth.uid()
 * happens to be set.
 *
 * The unique index on (league_id, player_name) is the backstop: if two adds
 * race, the second fails rather than the player landing on two rosters.
 */
create or replace function place_player(
  p_league_id uuid,
  p_manager_id uuid,
  p_add text,
  p_drop text default null,
  p_kind text default 'add'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_league   leagues;
  v_capacity int;
begin
  select * into v_league from leagues where id = p_league_id for update;
  if v_league.id is null then
    raise exception 'No such league' using errcode = 'P0002';
  end if;

  if not exists (
    select 1 from managers where id = p_manager_id and league_id = p_league_id
  ) then
    raise exception 'That manager is not in this league' using errcode = '42501';
  end if;

  if exists (
    select 1 from roster_slots where league_id = p_league_id and player_name = p_add
  ) then
    raise exception 'That player is already rostered' using errcode = '23505';
  end if;

  -- The drop happens first, so a full roster can take the incoming player.
  if p_drop is not null then
    delete from roster_slots
     where league_id = p_league_id and manager_id = p_manager_id and player_name = p_drop;

    if not found then
      raise exception 'You do not hold %', p_drop using errcode = 'P0002';
    end if;

    insert into transactions (league_id, manager_id, kind, player_name, detail)
    values (p_league_id, p_manager_id, 'drop', p_drop, jsonb_build_object('for', p_add));
  end if;

  v_capacity := roster_capacity(v_league.settings);
  if roster_count(p_manager_id) >= v_capacity then
    raise exception 'Your roster is full at % — drop someone first', v_capacity
      using errcode = '55000';
  end if;

  insert into roster_slots (league_id, manager_id, player_name, acquired, lineup_slot)
  values (p_league_id, p_manager_id, p_add, p_kind, 'BENCH');

  insert into transactions (league_id, manager_id, kind, player_name, detail)
  values (p_league_id, p_manager_id, p_kind, p_add, jsonb_build_object('dropped', p_drop));

  return jsonb_build_object('ok', true, 'added', p_add, 'dropped', p_drop);
end;
$$;

-- Nobody calls this directly: it does not check who is asking.
revoke all on function place_player(uuid, uuid, text, text, text) from public;

/** Adds a player to the signed-in manager's own roster. */
create or replace function add_player(
  p_league_id uuid,
  p_add text,
  p_drop text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me managers;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null then
    raise exception 'Not signed in' using errcode = '28000';
  end if;
  if v_me.league_id <> p_league_id then
    raise exception 'Not your league' using errcode = '42501';
  end if;

  return place_player(p_league_id, v_me.id, p_add, p_drop, 'add');
end;
$$;

revoke all on function add_player(uuid, text, text) from public;
grant execute on function add_player(uuid, text, text) to authenticated;

/** Drops a player outright. */
create or replace function drop_player(p_league_id uuid, p_player text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me managers;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null or v_me.league_id <> p_league_id then
    raise exception 'Not your league' using errcode = '42501';
  end if;

  delete from roster_slots
   where league_id = p_league_id and manager_id = v_me.id and player_name = p_player;

  if not found then
    raise exception 'You do not hold %', p_player using errcode = 'P0002';
  end if;

  insert into transactions (league_id, manager_id, kind, player_name)
  values (p_league_id, v_me.id, 'drop', p_player);

  return jsonb_build_object('ok', true, 'dropped', p_player);
end;
$$;

revoke all on function drop_player(uuid, text) from public;
grant execute on function drop_player(uuid, text) to authenticated;

/**
 * Settles every pending claim in the league.
 *
 * Rolling priority: the best-priority manager with a live claim wins it, then
 * drops to the bottom of the order, and the next claim is judged against the
 * new order. That is why this is a loop rather than one ordered pass — a
 * single pass would let the best-priority manager sweep every player.
 *
 * A claim whose player was taken, or whose drop is no longer held, loses with
 * a reason rather than failing the whole run.
 */
create or replace function process_waivers(p_league_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_claim    waiver_claims;
  v_won      int := 0;
  v_lost     int := 0;
  v_max      int;
  v_guard    int := 0;
begin
  loop
    -- The next claim to judge: best waiver priority first, then the manager's
    -- own ordering, then the order it was placed.
    select c.* into v_claim
      from waiver_claims c
      join managers m on m.id = c.manager_id
     where c.league_id = p_league_id
       and c.status = 'pending'
     order by m.waiver_priority, c.claim_order, c.created_at
     limit 1;

    exit when v_claim.id is null;

    -- Bounded so a bug here can never spin forever against a live database.
    v_guard := v_guard + 1;
    exit when v_guard > 10000;

    begin
      perform place_player(
        p_league_id, v_claim.manager_id,
        v_claim.add_player, v_claim.drop_player, 'waiver'
      );

      update waiver_claims
         set status = 'won', settled_at = now()
       where id = v_claim.id;

      -- Winning sends this manager to the back of the queue, and everyone
      -- below them moves up one.
      select max(waiver_priority) into v_max
        from managers where league_id = p_league_id;

      update managers
         set waiver_priority = waiver_priority - 1
       where league_id = p_league_id
         and waiver_priority > (
           select waiver_priority from managers where id = v_claim.manager_id
         );

      update managers set waiver_priority = v_max where id = v_claim.manager_id;

      v_won := v_won + 1;

    exception when others then
      update waiver_claims
         set status = 'lost', reason = sqlerrm, settled_at = now()
       where id = v_claim.id;
      v_lost := v_lost + 1;
    end;
  end loop;

  return jsonb_build_object('ok', true, 'won', v_won, 'lost', v_lost);
end;
$$;

revoke all on function process_waivers(uuid) from public;


-- ======================================================================
-- 0008_schedule.sql
-- ======================================================================

-- The season schedule, and the standings that come from it.
--
-- Matchup used to pair managers by slot order, which meant there were no real
-- opponents and no records. This generates a round-robin, grades each week
-- from what the starters actually scored, and freezes a week once its games
-- are over — otherwise a lineup change in week 6 would silently rewrite the
-- result of week 5.

create table matchups (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references leagues(id) on delete cascade,
  week int not null,
  home_manager uuid references managers(id) on delete cascade,
  away_manager uuid references managers(id) on delete cascade,
  home_points numeric not null default 0,
  away_points numeric not null default 0,
  -- Who started, as they stood when the week was graded. Without this a later
  -- lineup change would make a finished week unexplainable.
  home_starters jsonb not null default '[]'::jsonb,
  away_starters jsonb not null default '[]'::jsonb,
  winner uuid references managers(id) on delete set null,
  is_tie boolean not null default false,
  final boolean not null default false,
  playoff boolean not null default false,
  graded_at timestamptz,
  unique (league_id, week, home_manager)
);

create index matchups_week_idx on matchups (league_id, week);

alter table matchups enable row level security;

create policy matchups_read on matchups
  for select using (league_id = (select league_id from current_manager()));

/**
 * Builds the regular season as a round robin.
 *
 * The circle method: one franchise is held still and the rest rotate around
 * it, so every manager meets every other before anyone is met twice. An odd
 * league pads with a phantom, and whoever draws it has a bye that week.
 *
 * Home and away alternate by week so the same pairing is not always the same
 * way round when the schedule wraps.
 *
 * Refuses once any week has been graded final — regenerating then would throw
 * away results that already stand.
 */
create or replace function generate_schedule(p_league_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_league  leagues;
  v_ids     uuid[];
  v_n       int;
  v_weeks   int;
  v_week    int;
  v_i       int;
  v_home    uuid;
  v_away    uuid;
  v_rot     uuid[];
  v_made    int := 0;
  v_byes    int := 0;
begin
  select * into v_league from leagues where id = p_league_id for update;
  if v_league.id is null then
    raise exception 'No such league' using errcode = 'P0002';
  end if;

  if exists (select 1 from matchups where league_id = p_league_id and final) then
    raise exception 'Weeks have already been played — the schedule is fixed now'
      using errcode = '55000';
  end if;

  select array_agg(id order by slot) into v_ids
    from managers where league_id = p_league_id;

  v_n := coalesce(array_length(v_ids, 1), 0);
  if v_n < 2 then
    raise exception 'A schedule needs at least two franchises' using errcode = '55000';
  end if;

  -- An odd league gets a phantom opponent; drawing it is a bye.
  if v_n % 2 = 1 then
    v_ids := v_ids || null::uuid;
    v_n := v_n + 1;
  end if;

  v_weeks := coalesce((v_league.settings ->> 'regularWeeks')::int, 13);

  delete from matchups where league_id = p_league_id and not final;

  v_rot := v_ids;

  for v_week in 1..v_weeks loop
    for v_i in 1..(v_n / 2) loop
      -- Alternate which side is home as the weeks go by.
      if v_week % 2 = 1 then
        v_home := v_rot[v_i];
        v_away := v_rot[v_n + 1 - v_i];
      else
        v_home := v_rot[v_n + 1 - v_i];
        v_away := v_rot[v_i];
      end if;

      if v_home is null or v_away is null then
        v_byes := v_byes + 1;
        continue;
      end if;

      insert into matchups (league_id, week, home_manager, away_manager)
      values (p_league_id, v_week, v_home, v_away);
      v_made := v_made + 1;
    end loop;

    -- Rotate every position but the first.
    v_rot := array[v_rot[1]] || v_rot[v_n] || v_rot[2:v_n - 1];
  end loop;

  return jsonb_build_object('ok', true, 'weeks', v_weeks, 'matchups', v_made, 'byes', v_byes);
end;
$$;

revoke all on function generate_schedule(uuid) from public;

/** The commissioner's way in. */
create or replace function commissioner_generate_schedule(p_league_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me managers;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null or not v_me.is_commissioner or v_me.league_id <> p_league_id then
    raise exception 'Only the commissioner can build the schedule' using errcode = '42501';
  end if;

  return generate_schedule(p_league_id);
end;
$$;

revoke all on function commissioner_generate_schedule(uuid) from public;
grant execute on function commissioner_generate_schedule(uuid) to authenticated;

/** What a manager's starters scored in a week. */
create or replace function lineup_points(p_league_id uuid, p_manager_id uuid, p_week int)
returns numeric
language sql
stable
as $$
  select coalesce(sum(s.points), 0)
    from roster_slots r
    join player_scores s
      on s.league_id = r.league_id
     and s.player_name = r.player_name
     and s.week = p_week
   where r.league_id = p_league_id
     and r.manager_id = p_manager_id
     and r.lineup_slot not in ('BENCH', 'IR');
$$;

/**
 * Scores a week and, once its games are over, freezes the result.
 *
 * A week stays open while games are still to be played, so live scores move
 * during the day. It goes final only when every game that week is complete,
 * and a final week is never regraded — a manager changing their lineup in a
 * later week must not rewrite a result that already stands.
 */
create or replace function grade_week(p_league_id uuid, p_week int)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_m        matchups;
  v_complete boolean;
  v_graded   int := 0;
  v_home     numeric;
  v_away     numeric;
begin
  -- A week with no games mirrored yet cannot be closed.
  select count(*) > 0 and bool_and(completed)
    into v_complete
    from nfl_games where week = p_week;

  for v_m in
    select * from matchups
     where league_id = p_league_id and week = p_week and not final
  loop
    v_home := lineup_points(p_league_id, v_m.home_manager, p_week);
    v_away := lineup_points(p_league_id, v_m.away_manager, p_week);

    update matchups
       set home_points = v_home,
           away_points = v_away,
           home_starters = (
             select coalesce(jsonb_agg(jsonb_build_object('name', player_name, 'slot', lineup_slot)), '[]'::jsonb)
               from roster_slots
              where manager_id = v_m.home_manager and lineup_slot not in ('BENCH', 'IR')
           ),
           away_starters = (
             select coalesce(jsonb_agg(jsonb_build_object('name', player_name, 'slot', lineup_slot)), '[]'::jsonb)
               from roster_slots
              where manager_id = v_m.away_manager and lineup_slot not in ('BENCH', 'IR')
           ),
           winner = case
             when not coalesce(v_complete, false) then null
             when v_home > v_away then v_m.home_manager
             when v_away > v_home then v_m.away_manager
             else null
           end,
           is_tie = coalesce(v_complete, false) and v_home = v_away,
           final = coalesce(v_complete, false),
           graded_at = now()
     where id = v_m.id;

    v_graded := v_graded + 1;
  end loop;

  return jsonb_build_object('ok', true, 'week', p_week, 'graded', v_graded, 'final', coalesce(v_complete, false));
end;
$$;

revoke all on function grade_week(uuid, int) from public;

/**
 * The table. Only final weeks count toward a record — a week still being
 * played shows in the live matchup, not in the standings.
 */
create or replace function standings(p_league_id uuid)
returns table (
  manager_id uuid,
  slot text,
  franchise text,
  wins int,
  losses int,
  ties int,
  points_for numeric,
  points_against numeric
)
language sql
stable
as $$
  with sides as (
    select home_manager as manager_id, home_points as pf, away_points as pa,
           winner, is_tie, final
      from matchups where league_id = p_league_id
    union all
    select away_manager, away_points, home_points, winner, is_tie, final
      from matchups where league_id = p_league_id
  )
  select m.id,
         m.slot,
         m.franchise,
         count(*) filter (where s.final and s.winner = m.id)::int,
         count(*) filter (where s.final and s.winner is not null and s.winner <> m.id)::int,
         count(*) filter (where s.final and s.is_tie)::int,
         coalesce(sum(s.pf) filter (where s.final), 0),
         coalesce(sum(s.pa) filter (where s.final), 0)
    from managers m
    left join sides s on s.manager_id = m.id
   where m.league_id = p_league_id
   group by m.id, m.slot, m.franchise
   order by 4 desc, 7 desc;
$$;


-- ======================================================================
-- 0009_divisions.sql
-- ======================================================================

-- Two divisions, with divisional rivals met twice.
--
-- The season is built in two phases:
--   1. A full round robin — everyone plays everyone once.       (n-1 weeks)
--   2. A round robin inside each division, both running at the
--      same time, giving every divisional rival a second game.  (n/2-1 weeks)
--
-- So the shape of the league decides the length of the season, not the other
-- way round: twelve franchises means sixteen regular weeks. generate_schedule
-- writes that length back onto the league so playoffs and the rest of the app
-- agree with the schedule that actually exists.

alter table managers
  add column if not exists division text;

-- Split by slot for a league that has none, so divisions are defined from the
-- first schedule rather than being null.
update managers m
   set division = case when seq.rn * 2 <= seq.total then 'East' else 'West' end
  from (
    select id,
           row_number() over (partition by league_id order by slot) as rn,
           count(*) over (partition by league_id) as total
      from managers
  ) seq
 where seq.id = m.id and m.division is null;

alter table matchups
  add column if not exists divisional boolean not null default false;

/**
 * One round robin, by the circle method: the first entry is held still and the
 * rest rotate around it, so everyone meets everyone before anyone repeats. An
 * odd list is padded, and a pairing against the padding is a bye — returned as
 * no row rather than a broken fixture.
 *
 * Home and away alternate by round so a pairing is not always the same way
 * round when this is used twice.
 */
create or replace function round_robin(p_ids uuid[])
returns table (rnd int, home uuid, away uuid)
language plpgsql
immutable
as $$
declare
  v_ids uuid[] := p_ids;
  v_n   int;
  v_r   int;
  v_i   int;
  v_h   uuid;
  v_a   uuid;
begin
  v_n := coalesce(array_length(v_ids, 1), 0);
  if v_n < 2 then return; end if;

  if v_n % 2 = 1 then
    v_ids := v_ids || null::uuid;
    v_n := v_n + 1;
  end if;

  for v_r in 1..(v_n - 1) loop
    for v_i in 1..(v_n / 2) loop
      if v_r % 2 = 1 then
        v_h := v_ids[v_i];
        v_a := v_ids[v_n + 1 - v_i];
      else
        v_h := v_ids[v_n + 1 - v_i];
        v_a := v_ids[v_i];
      end if;

      if v_h is not null and v_a is not null then
        rnd := v_r; home := v_h; away := v_a;
        return next;
      end if;
    end loop;

    -- Rotate everything but the first position.
    v_ids := array[v_ids[1]] || v_ids[v_n] || v_ids[2:v_n - 1];
  end loop;
end;
$$;

create or replace function generate_schedule(p_league_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_league    leagues;
  v_all       uuid[];
  v_divs      text[];
  v_div       text;
  v_ids       uuid[];
  v_n         int;
  v_phase1    int := 0;
  v_phase2    int := 0;
  v_rows      record;
  v_made      int := 0;
  v_byes      int := 0;
  v_divisional int := 0;
begin
  select * into v_league from leagues where id = p_league_id for update;
  if v_league.id is null then
    raise exception 'No such league' using errcode = 'P0002';
  end if;

  if exists (select 1 from matchups where league_id = p_league_id and final) then
    raise exception 'Weeks have already been played — the schedule is fixed now'
      using errcode = '55000';
  end if;

  select array_agg(id order by slot) into v_all
    from managers where league_id = p_league_id;

  v_n := coalesce(array_length(v_all, 1), 0);
  if v_n < 2 then
    raise exception 'A schedule needs at least two franchises' using errcode = '55000';
  end if;

  delete from matchups where league_id = p_league_id and not final;

  -- Phase one: everyone plays everyone once.
  for v_rows in select * from round_robin(v_all) loop
    insert into matchups (league_id, week, home_manager, away_manager, divisional)
    values (
      p_league_id, v_rows.rnd, v_rows.home, v_rows.away,
      (select m1.division from managers m1 where m1.id = v_rows.home)
        is not distinct from
      (select m2.division from managers m2 where m2.id = v_rows.away)
    );
    v_made := v_made + 1;
    v_phase1 := greatest(v_phase1, v_rows.rnd);
  end loop;

  -- A padded round robin has as many rounds as the padded size minus one, so
  -- an odd league still spans that many weeks even where a row is a bye.
  v_phase1 := case when v_n % 2 = 1 then v_n else v_n - 1 end;

  -- Phase two: the divisional rematches. Both divisions run at the same time,
  -- because they share no franchises.
  select array_agg(distinct division order by division) into v_divs
    from managers where league_id = p_league_id and division is not null;

  if v_divs is not null then
    foreach v_div in array v_divs loop
      select array_agg(id order by slot) into v_ids
        from managers where league_id = p_league_id and division = v_div;

      for v_rows in select * from round_robin(v_ids) loop
        insert into matchups (league_id, week, home_manager, away_manager, divisional)
        values (p_league_id, v_phase1 + v_rows.rnd, v_rows.home, v_rows.away, true);
        v_made := v_made + 1;
        v_phase2 := greatest(v_phase2, v_rows.rnd);
      end loop;
    end loop;
  end if;

  select count(*) into v_divisional
    from matchups where league_id = p_league_id and divisional;

  -- Somebody sits out any week where the pairing fell against the padding.
  select (v_phase1 + v_phase2) * (v_n / 2) - v_made into v_byes;

  -- The schedule decides the season length, so the setting follows it rather
  -- than silently disagreeing with the fixtures that exist.
  update leagues
     set settings = jsonb_set(
           coalesce(settings, '{}'::jsonb),
           '{regularWeeks}',
           to_jsonb(v_phase1 + v_phase2)
         )
   where id = p_league_id;

  return jsonb_build_object(
    'ok', true,
    'weeks', v_phase1 + v_phase2,
    'matchups', v_made,
    'divisional', v_divisional,
    'byes', greatest(v_byes, 0)
  );
end;
$$;

revoke all on function generate_schedule(uuid) from public;

/** Moves a franchise to a division. Refused once a week has been played. */
create or replace function set_division(p_manager_id uuid, p_division text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me managers;
begin
  select * into v_me from managers where auth_user_id = auth.uid();
  if v_me.id is null or not v_me.is_commissioner then
    raise exception 'Only the commissioner can set divisions' using errcode = '42501';
  end if;

  if exists (select 1 from matchups where league_id = v_me.league_id and final) then
    raise exception 'Weeks have already been played — divisions are fixed now'
      using errcode = '55000';
  end if;

  update managers set division = p_division
   where id = p_manager_id and league_id = v_me.league_id;

  if not found then
    raise exception 'No such manager in your league' using errcode = 'P0002';
  end if;

  insert into admin_log (league_id, actor, action, detail)
  values (v_me.league_id, v_me.id, 'division',
          jsonb_build_object('manager_id', p_manager_id, 'division', p_division));

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function set_division(uuid, text) from public;
grant execute on function set_division(uuid, text) to authenticated;

/** Standings, now carrying the division and the record inside it. */
-- The shape of the result changes, so the old one is dropped first.
drop function if exists standings(uuid);

create or replace function standings(p_league_id uuid)
returns table (
  manager_id uuid,
  slot text,
  franchise text,
  division text,
  wins int,
  losses int,
  ties int,
  div_wins int,
  div_losses int,
  points_for numeric,
  points_against numeric
)
language sql
stable
as $$
  with sides as (
    select home_manager as manager_id, home_points as pf, away_points as pa,
           winner, is_tie, final, divisional
      from matchups where league_id = p_league_id
    union all
    select away_manager, away_points, home_points, winner, is_tie, final, divisional
      from matchups where league_id = p_league_id
  )
  select m.id,
         m.slot,
         m.franchise,
         m.division,
         count(*) filter (where s.final and s.winner = m.id)::int,
         count(*) filter (where s.final and s.winner is not null and s.winner <> m.id)::int,
         count(*) filter (where s.final and s.is_tie)::int,
         count(*) filter (where s.final and s.divisional and s.winner = m.id)::int,
         count(*) filter (where s.final and s.divisional and s.winner is not null and s.winner <> m.id)::int,
         coalesce(sum(s.pf) filter (where s.final), 0),
         coalesce(sum(s.pa) filter (where s.final), 0)
    from managers m
    left join sides s on s.manager_id = m.id
   where m.league_id = p_league_id
   group by m.id, m.slot, m.franchise, m.division
   order by m.division, 5 desc, 10 desc;
$$;


/**
 * A franchise added by a resize has no division, which would leave it out of
 * the divisional rematches. New slots join the smaller division, so the two
 * stay as even as the league allows.
 */
create or replace function assign_missing_divisions(p_league_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id    uuid;
  v_divs  text[];
  v_small text;
begin
  select array_agg(distinct division order by division) into v_divs
    from managers where league_id = p_league_id and division is not null;

  -- A league with no divisions at all splits evenly by slot.
  if v_divs is null or array_length(v_divs, 1) < 2 then
    update managers m
       set division = case when seq.rn * 2 <= seq.total then 'East' else 'West' end
      from (
        select id,
               row_number() over (order by slot) as rn,
               count(*) over () as total
          from managers where league_id = p_league_id
      ) seq
     where seq.id = m.id;
    return;
  end if;

  for v_id in
    select id from managers
     where league_id = p_league_id and division is null
     order by slot
  loop
    select division into v_small
      from managers
     where league_id = p_league_id and division is not null
     group by division
     order by count(*), division
     limit 1;

    update managers set division = v_small where id = v_id;
  end loop;
end;
$$;

revoke all on function assign_missing_divisions(uuid) from public;

-- Any franchise created later — by a resize, or by the seed script — joins a
-- division automatically, so a league can never end up with a franchise that
-- sits outside the divisional rematches.
create or replace function assign_division_on_insert()
returns trigger
language plpgsql
as $$
declare
  v_divs  text[];
  v_small text;
begin
  if new.division is not null then return new; end if;

  select array_agg(distinct division order by division) into v_divs
    from managers where league_id = new.league_id and division is not null;

  -- A league that has not got two divisions yet is filling the first ones, so
  -- both names have to be candidates: picking the smallest of what exists
  -- would put everybody in whichever division was created first.
  if v_divs is null or array_length(v_divs, 1) < 2 then
    v_divs := array['East', 'West'];
  end if;

  select d into v_small
    from unnest(v_divs) as d
    left join managers m
      on m.league_id = new.league_id and m.division = d
   group by d
   order by count(m.id), d
   limit 1;

  new.division := coalesce(v_small, 'East');
  return new;
end;
$$;

drop trigger if exists managers_division on managers;
create trigger managers_division
  before insert on managers
  for each row execute function assign_division_on_insert();


commit;

-- If this ran without error, the schema is in place. Next: seed the league.
--
--   node scripts/seed.mjs --teams 12
